INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMPCODE, SALARY) VALUES (1, "Rajeev1", "SK1", "EMP001", 1000.00);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMPCODE, SALARY) VALUES (2, "Rajeev2", "SK2", "EMP002", 2000.00);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMPCODE, SALARY) VALUES (3, "Rajeev3", "SK3", "EMP003", 3000.00);