CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(10) NOT NULL,
    LAST_NAME VARCHAR(10) NOT NULL,
    EMPCODE VARCHAR(10) NOT NULL,
    SALARY DOUBLE NOT NULL
);